# Generated by Django 6.1 on 2026-08-19 23:00

import uuid

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0143_event_rule_action_registry'),
        ('users', '0016_default_ordering_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('api_url', models.URLField()),
                ('namespace', models.CharField(blank=True, max_length=200)),
                ('kv_mount', models.CharField(default='secret', max_length=100)),
                ('kv_version', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('auth_method', models.CharField(default='approle', max_length=50)),
                ('tls_verify', models.BooleanField(default=True)),
                ('ca_cert_path', models.CharField(blank=True, max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(default='unknown', editable=False, max_length=50)),
                ('last_checked', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status_message', models.CharField(blank=True, editable=False, max_length=500)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'secret engine',
                'verbose_name_plural': 'secret engines',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CredentialPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('openbao_policy', models.CharField(max_length=200)),
                ('approle_env_prefix', models.CharField(blank=True, max_length=100)),
                ('max_reveal_ttl', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1)])),
                ('require_reason', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='openbao_credential_policies', to='users.group')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='netbox_openbao.secretengine')),
            ],
            options={
                'verbose_name': 'credential policy',
                'verbose_name_plural': 'credential policies',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('credential_type', models.CharField(max_length=50)),
                ('path', models.CharField(db_index=True, editable=False, max_length=500)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('public_key', models.TextField(blank=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('key_type', models.CharField(blank=True, max_length=50)),
                ('cert_serial', models.CharField(blank=True, max_length=128)),
                ('cert_subject', models.CharField(blank=True, max_length=500)),
                ('cert_issuer', models.CharField(blank=True, max_length=500)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('rotation_interval', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('last_rotated', models.DateTimeField(blank=True, null=True)),
                ('kv_version', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('last_verified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='netbox_openbao.credentialpolicy')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='netbox_openbao.secretengine')),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credentials',
                'ordering': ('name', 'pk'),
                'permissions': (('reveal', 'Reveal secret material'), ('rotate', 'Rotate secret material')),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CredentialAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('credential_name_snapshot', models.CharField(max_length=200)),
                ('credential_uuid_snapshot', models.UUIDField(blank=True, null=True)),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=50)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='netbox_openbao.credential')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credential access log',
                'verbose_name_plural': 'credential access logs',
                'ordering': ('-timestamp', '-pk'),
                'indexes': [models.Index(fields=['credential', '-timestamp'], name='netbox_open_credent_efb212_idx'), models.Index(fields=['user', '-timestamp'], name='netbox_open_user_id_45ce56_idx')],
            },
        ),
        migrations.CreateModel(
            name='CredentialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(default='login', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('assigned_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='netbox_openbao.credential')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'credential assignment',
                'verbose_name_plural': 'credential assignments',
                'ordering': ('credential', 'pk'),
                'indexes': [models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='netbox_open_assigne_7d4b48_idx')],
                'constraints': [models.UniqueConstraint(fields=('credential', 'assigned_object_type', 'assigned_object_id', 'purpose'), name='netbox_openbao_credentialassignment_unique_assignment', violation_error_message='This credential is already assigned to that object for that purpose.'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('assigned_object_type', 'assigned_object_id', 'purpose'), name='netbox_openbao_credentialassignment_single_primary', violation_error_message='Another credential is already primary for that object and purpose.')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='secretengine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='netbox_openbao_secretengine_single_default', violation_error_message='Another engine is already marked as the default.'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['credential_type', 'status'], name='netbox_open_credent_c0eefb_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['valid_until'], name='netbox_open_valid_u_1f85e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.UniqueConstraint(fields=('engine', 'path'), name='netbox_openbao_credential_unique_engine_path', violation_error_message='A credential already occupies this path on this engine.'),
        ),
    ]
