# Generated by Django 6.1 on 2026-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_openbao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='live_kv_version',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='staged_kv_version',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
