# Generated by Django 6.1 on 2026-08-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_openbao', '0002_credential_live_kv_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretengine',
            name='backend',
            field=models.CharField(default='openbao', max_length=50),
        ),
    ]
