# Generated by Django 6.1 on 2026-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_openbao', '0003_secretengine_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='import_source',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200),
        ),
    ]
