# Generated by Django 6.1 on 2026-08-20 15:55

import django.contrib.postgres.fields
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # The oldest `extras` node that satisfies what these models actually
        # need, which is `Tag` and `TaggedItem` for `TaggableManager`. It was
        # `0143_event_rule_action_registry` - the 4.7 tip at the time of
        # writing - which does not exist on 4.6 and made the whole migration
        # graph unloadable there, not merely this app's part of it.
        #
        # 0138 is 4.6's tip and is in 4.7's history (4.7 added 0139-0143 on top
        # of it), so it resolves on both. Depending on the current tip of
        # another app pins you to that release for no benefit; depend on the
        # thing you use.
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_openbao', '0004_credential_import_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialTypeSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('schema', models.JSONField()),
                ('secret_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('extractor', models.CharField(blank=True, max_length=50)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'credential type schema',
                'verbose_name_plural': 'credential type schemas',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
