# Generated by Django 6.1 on 2026-09-02

import django.contrib.postgres.fields
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models

import netbox_openbao.models.settings

MODEL_DEFAULTS = {
    'path_prefix': 'netbox',
    'assignable_models': [
        'dcim.device',
        'virtualization.virtualmachine',
        'ipam.service',
    ],
    'assignable_models_deny': [],
    'store_public_material': True,
    'reveal_rate_limit': '30/hour',
    'reveal_ttl': 300,
    'token_cache_ttl': 3600,
    'audit_retention_days': 365,
    'allow_generation': True,
    'default_ssh_key_type': 'ed25519',
    'expiry_warning_days': [30, 14, 7, 1],
    'engine_health_interval': 5,
    'expiry_scan_interval': 1440,
    'credential_verify_interval': 1440,
    'rotation_due_interval': 1440,
    'access_log_prune_interval': 10080,
}

ORDER_INSENSITIVE_SETTINGS = {
    'assignable_models',
    'assignable_models_deny',
    'expiry_warning_days',
}
LABEL_SETTINGS = {
    'assignable_models',
    'assignable_models_deny',
}


def _canonical_settings(values):
    """Apply the same set-like semantics used by the runtime read path."""
    canonical = {}
    for key, value in values.items():
        if isinstance(value, tuple):
            value = list(value)
        if key in LABEL_SETTINGS:
            # assignable_model_labels() strips and lowercases labels, ignores
            # empty/non-string entries, and treats the result as a set. The
            # migration comparison must do exactly the same or a spelling-only
            # difference creates an authoritative row that freezes later
            # PLUGINS_CONFIG changes.
            value = sorted({
                label.strip().lower()
                for label in (value or [])
                if isinstance(label, str) and label.strip()
            })
        elif key in ORDER_INSENSITIVE_SETTINGS:
            value = sorted(value)
        canonical[key] = value
    return canonical


def _valid_path_prefix(prefix):
    """Mirror the runtime model's structural path validation."""
    if not isinstance(prefix, str):
        return False
    segments = prefix.split('/')
    return not (
        not prefix
        or prefix.startswith('/')
        or prefix.endswith('/')
        or any(character.isspace() for character in prefix)
        or any(segment in ('', '.', '..') for segment in segments)
    )


def seed_settings(apps, schema_editor):
    """Preserve non-default PLUGINS_CONFIG values on upgrade."""
    OpenBaoSettings = apps.get_model('netbox_openbao', 'OpenBaoSettings')
    if OpenBaoSettings.objects.filter(singleton_key='default').exists():
        return

    configured = settings.PLUGINS_CONFIG.get('netbox_openbao', {})
    values = {}
    for key, default in MODEL_DEFAULTS.items():
        value = configured.get(key, default)
        value = default if value is None else value
        values[key] = list(value) if isinstance(value, tuple) else value
    values = _canonical_settings(values)

    # NetBox merges PluginConfig.default_settings into PLUGINS_CONFIG during
    # startup. Avoid creating a row when that merged mapping contains only the
    # defaults: a no-row installation retains the live PLUGINS_CONFIG fallback
    # used by override_settings and fresh deployments. A deployment with any
    # effective customization gets the complete row, so its upgrade is inert.
    if _canonical_settings(values) == _canonical_settings(MODEL_DEFAULTS):
        return

    # Historical models do not expose the current model's clean() method, and
    # objects.create() never validates in Django. Keep an unsafe legacy prefix
    # on the existing PLUGINS_CONFIG fallback rather than making it an
    # authoritative database value that the runtime model itself would refuse.
    if not _valid_path_prefix(values['path_prefix']):
        return

    OpenBaoSettings.objects.create(singleton_key='default', **values)


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_openbao', '0007_secretengine_host_device_openbaoprocedurerun'),
    ]

    operations = [
        # 0007 introduced another NetBoxModel but omitted the custom-field
        # encoder inherited from core. Recording it here keeps migration state
        # aligned on both supported NetBox releases; this changes no column.
        migrations.AlterField(
            model_name='openbaoprocedurerun',
            name='custom_field_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=utilities.json.CustomFieldJSONEncoder,
            ),
        ),
        migrations.CreateModel(
            name='OpenBaoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    'singleton_key',
                    models.CharField(default='default', editable=False, max_length=32, unique=True),
                ),
                ('path_prefix', models.CharField(default='netbox', max_length=200, verbose_name='path prefix')),
                (
                    'assignable_models',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=netbox_openbao.models.settings._default_assignable_models,
                        size=None,
                        verbose_name='assignable models',
                    ),
                ),
                (
                    'assignable_models_deny',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name='denied assignable models',
                    ),
                ),
                ('store_public_material', models.BooleanField(default=True, verbose_name='store public material')),
                (
                    'reveal_rate_limit',
                    models.CharField(
                        default='30/hour',
                        max_length=64,
                        validators=(netbox_openbao.models.settings.validate_reveal_rate,),
                        verbose_name='reveal rate limit',
                    ),
                ),
                ('reveal_ttl', models.PositiveIntegerField(default=300, verbose_name='reveal TTL')),
                ('token_cache_ttl', models.PositiveIntegerField(default=3600, verbose_name='token cache TTL')),
                (
                    'audit_retention_days',
                    models.PositiveIntegerField(default=365, verbose_name='audit retention days'),
                ),
                ('allow_generation', models.BooleanField(default=True, verbose_name='allow generation')),
                (
                    'default_ssh_key_type',
                    models.CharField(default='ed25519', max_length=32, verbose_name='default SSH key type'),
                ),
                (
                    'expiry_warning_days',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=netbox_openbao.models.settings._default_expiry_warning_days,
                        size=None,
                        verbose_name='expiry warning days',
                    ),
                ),
                (
                    'engine_health_interval',
                    models.PositiveIntegerField(default=5, verbose_name='engine health interval'),
                ),
                (
                    'expiry_scan_interval',
                    models.PositiveIntegerField(default=1440, verbose_name='expiry scan interval'),
                ),
                (
                    'credential_verify_interval',
                    models.PositiveIntegerField(default=1440, verbose_name='credential verification interval'),
                ),
                (
                    'rotation_due_interval',
                    models.PositiveIntegerField(default=1440, verbose_name='rotation due interval'),
                ),
                (
                    'access_log_prune_interval',
                    models.PositiveIntegerField(default=10080, verbose_name='access-log prune interval'),
                ),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'OpenBao settings',
                'verbose_name_plural': 'OpenBao settings',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.RunPython(seed_settings, migrations.RunPython.noop),
    ]
