from django.db import migrations

PERMISSIONS = (
    ("discover", "Discover OpenBao administrative capabilities"),
    ("operate", "Run non-sensitive OpenBao administrative operations"),
    ("operate_sensitive", "Run material-bearing OpenBao administrative operations"),
    ("operate_destructive", "Run destructive OpenBao administrative operations"),
    ("initialize", "Initialize an OpenBao cluster"),
    ("unseal", "Submit OpenBao unseal material or reset unseal progress"),
    ("seal", "Seal an OpenBao cluster"),
    ("manage_raft", "Manage OpenBao Raft configuration"),
    ("join_raft", "Join an OpenBao Raft cluster"),
    ("remove_raft_peer", "Remove an OpenBao Raft peer"),
    ("download_raft_snapshot", "Download an OpenBao Raft snapshot"),
    ("restore_raft_snapshot", "Restore an OpenBao Raft snapshot"),
    ("force_restore_raft_snapshot", "Force restore an OpenBao Raft snapshot"),
    ("view_authentication", "View OpenBao authentication and MFA configuration"),
    ("manage_auth_methods", "Enable, configure, tune, and remount OpenBao auth methods"),
    ("disable_auth_methods", "Disable OpenBao auth methods"),
    ("manage_auth_resources", "Manage OpenBao auth method resources"),
    ("delete_auth_resources", "Delete OpenBao auth method resources"),
    ("issue_auth_material", "Issue one-shot OpenBao authentication material"),
    ("authenticate", "Use OpenBao authentication and MFA flows"),
    ("manage_tokens", "Look up and renew OpenBao tokens"),
    ("revoke_tokens", "Revoke OpenBao tokens"),
    ("manage_mfa", "Manage OpenBao MFA methods and login enforcements"),
    ("delete_mfa", "Delete OpenBao MFA methods, secrets, and login enforcements"),
    ("view_secret_engines", "View OpenBao secrets-engine configuration"),
    ("manage_secret_engines", "Enable, tune, and remount OpenBao secrets engines"),
    ("disable_secret_engines", "Disable OpenBao secrets engines"),
    ("explore_secret_operations", "View classified OpenBao mounted operations"),
    ("execute_secret_operations", "Execute write operations on OpenBao secrets engines"),
    ("delete_secret_operations", "Delete or destroy mounted OpenBao secret resources"),
    ("reveal_secret_operations", "Read material-bearing OpenBao secrets-engine responses"),
    ("reveal_kv_secrets", "Read KV secret values, metadata, versions, and diffs"),
    ("manage_kv_secrets", "Create, update, patch, undelete, and configure KV secrets"),
    ("destroy_kv_versions", "Delete or irreversibly destroy KV secrets and versions"),
    ("use_transit", "Use OpenBao transit cryptographic operations"),
    ("manage_transit_keys", "Create, configure, and rotate OpenBao transit keys"),
    ("delete_transit_keys", "Delete OpenBao transit keys"),
    ("generate_database_credentials", "Generate OpenBao database credentials"),
    ("manage_database_roles", "Manage OpenBao database connections and roles"),
    ("delete_database_resources", "Delete OpenBao database connections and roles"),
    ("rotate_database_credentials", "Rotate OpenBao database credentials and connections"),
    ("issue_ssh_credentials", "Issue and verify OpenBao SSH credentials and certificates"),
    ("manage_ssh_roles", "Manage OpenBao SSH roles"),
    ("delete_ssh_roles", "Delete OpenBao SSH roles"),
    ("generate_totp_codes", "Generate and validate OpenBao TOTP codes"),
    ("manage_totp_keys", "Create and view OpenBao TOTP keys"),
    ("delete_totp_keys", "Delete OpenBao TOTP keys"),
    ("view_pki", "View OpenBao PKI configuration and resources"),
    ("manage_pki_configuration", "Manage OpenBao PKI configuration"),
    ("manage_pki_issuers", "Import and manage OpenBao PKI issuers"),
    ("delete_pki_issuers", "Delete OpenBao PKI issuers"),
    ("manage_pki_keys", "Import and manage OpenBao PKI keys"),
    ("generate_pki_keys", "Generate OpenBao PKI keys"),
    ("delete_pki_keys", "Delete OpenBao PKI keys"),
    ("manage_pki_roles", "Manage OpenBao PKI roles"),
    ("delete_pki_roles", "Delete OpenBao PKI roles"),
    ("issue_pki_certificates", "Issue and sign OpenBao PKI certificates"),
    ("revoke_pki_certificates", "Revoke OpenBao PKI certificates"),
    ("rotate_pki_roots", "Generate and rotate OpenBao PKI roots"),
    ("delete_pki_roots", "Delete all OpenBao PKI issuers and keys"),
    ("tidy_pki", "Run and configure OpenBao PKI tidy operations"),
    ("view_kubernetes_engine", "View OpenBao Kubernetes secrets-engine configuration"),
    ("manage_k8s_configuration", "Manage OpenBao Kubernetes secrets-engine configuration"),
    ("delete_k8s_configuration", "Delete OpenBao Kubernetes secrets-engine configuration"),
    ("manage_kubernetes_roles", "Manage OpenBao Kubernetes secrets-engine roles"),
    ("delete_kubernetes_roles", "Delete OpenBao Kubernetes secrets-engine roles"),
    ("generate_k8s_credentials", "Generate OpenBao Kubernetes credentials"),
    ("view_access", "View OpenBao policies, identity, OIDC, and namespaces"),
    ("manage_policies", "Create and update OpenBao policies"),
    ("delete_policies", "Delete OpenBao policies"),
    ("generate_passwords", "Generate passwords from OpenBao password policies"),
    ("manage_identity", "Create and update OpenBao identity resources"),
    ("delete_identity", "Delete OpenBao identity resources"),
    ("merge_identity", "Merge OpenBao identity entities"),
    ("manage_oidc", "Create and update OpenBao OIDC resources"),
    ("reveal_oidc_client_secrets", "Read generated OpenBao OIDC client credentials"),
    ("delete_oidc", "Delete OpenBao OIDC resources"),
    ("rotate_oidc_keys", "Rotate OpenBao OIDC signing keys"),
    ("manage_namespaces", "Create and update OpenBao namespaces"),
    ("delete_namespaces", "Delete OpenBao namespaces"),
    ("view_operations", "View OpenBao leases, tools, and UI configuration"),
    ("view_leases", "View OpenBao leases"),
    ("manage_leases", "Renew OpenBao leases"),
    ("revoke_leases", "Revoke OpenBao leases and prefixes"),
    ("force_revoke_leases", "Force revoke OpenBao lease prefixes"),
    ("use_wrapping", "Wrap, inspect, and rewrap OpenBao responses"),
    ("unwrap_material", "Unwrap one-time OpenBao response material"),
    ("use_tools", "Use OpenBao hashing and random-data tools"),
    ("view_ui_configuration", "View OpenBao UI response-header configuration"),
    ("manage_ui_configuration", "Replace and delete OpenBao UI response headers"),
)


class Migration(migrations.Migration):
    dependencies = [("netbox_openbao", "0019_administration_log_targets")]
    operations = [
        migrations.AlterModelOptions(
            name="openbaocluster",
            options={
                "ordering": ("name",),
                "permissions": PERMISSIONS,
                "verbose_name": "OpenBao cluster",
                "verbose_name_plural": "OpenBao clusters",
            },
        )
    ]
